name: macOS Intel Release

on:
  workflow_dispatch:
    branches: [ "master" ]

env:
  SOURCE_DIR:   ${{ github.workspace }}/platform
  QTDIR:        /usr/local/Cellar/qt@5/5.15.12/bin
  ARTIFACT:     ${{ github.workspace }}/platform/build/MLV\ App.dmg

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install llvm & Qt & OpenSSL
      uses: ConorMacBride/install-package@v1.1.0
      with:
        brew: llvm qt5 openssl
              
    - name: Create build directory
      run:  mkdir ${{ env.SOURCE_DIR }}/build

    - name: Build
      working-directory: ${{ env.SOURCE_DIR }}/build
      run:  |
            ${{ env.QTDIR }}/qmake -r ${{ env.SOURCE_DIR }}/qt/MLVApp.pro
            make -j8
            ls -al
            ${{ env.QTDIR }}/macdeployqt MLV\ App.app -dmg

    - name: Save build artifact
      uses: actions/upload-artifact@master
      with:
        name: MLVApp macOS Intel
        path: ${{ env.ARTIFACT }}
